export const routes = {
  // Auth screens
  WELCOME: 'WELCOME',
  LOGIN: 'LOGIN',
  VERIFY_OTP: 'VERIFY_OTP',

  // Main screens
  MAIN_BOTTOM_TAB: 'MAIN_BOTTOM_TAB',
  MAIN_HOME: 'Home',
  MAIN_WEATHER: 'Weather',
  MAIN_SETTINGS: 'Settings',
  MAIN_TEST: 'Test',

  // Other navigation
  ENTER_LOCATION: 'ENTER_LOCATION',
  LOST_CONNECTION: 'LOST_CONNECTION',
  WEATHER_TRACKING: 'WEATHER_TRACKING',
  CHAT: 'CHAT',
  CHAT_LIST: 'CHAT_LIST',
  ADD_TODO: 'ADD_TODO',
  TODO: 'TODO',
};
